Repository process-analytics/bpmn-visualization-R, pull requests merged in 2021-09, with the labels that each got.

#42 [DOC] Explain how to integrate in Shiny Applications
  README.md
Labels: documentation

#41 [DOC] Document the release process
  CONTRIBUTING.md
  doc/cran-submitting.png
  doc/r-studio-binary-build.png
Labels: documentation

#39 [DOC] Improve project description and README
  DESCRIPTION
  README.md
Labels: documentation

#46 [FIX] Manage adding overlays referencing an unknown bpmn element
  inst/htmlwidgets/bpmnVisualization.js
Labels: bug

#48 [INFRA] Integrate feedback of the first release
  .Rbuildignore
  .github/workflows/R-CMD-check.yaml
  CONTRIBUTING.md
  DESCRIPTION
  doc/cran-submitting.png
  doc/r-studio-binary-build.png
Labels: infra:build

#49 [INFRA] Clean warnings to facilitate CRAN submission
  .github/workflows/R-CMD-check.yaml
  DESCRIPTION
  man/bpmnVisualization-package.Rd
Labels: infra:repo

#51 [DOC] Fix the link of the Code of conduct
  README.md
Labels: documentation

#52 [DOC] Fix the documentation to create an overlay
  README.md
Labels: documentation
