Repository process-analytics/bpmn-visualization-R, pull requests merged in 2021-08, with the labels that each got.

#1 [DOC] Update ReadMe & add Contributing guide
  .gitignore
  CONTRIBUTING.md
  README.md
Labels: documentation

#26 [FEAT] Display a BPMN diagram
  .Rbuildignore
  .gitignore
  CONTRIBUTING.md
  DESCRIPTION
  NAMESPACE
  R/bpmnVisualization.R
  README.md
  inst/examples/Email_Voting.bpmn
  inst/examples/Nobel_Prize_Process.bpmn
  inst/examples/Order_Process_for_Pizza_V4.bpmn
  inst/examples/Travel_Booking.bpmn
  inst/htmlwidgets/bpmnVisualization.js
  inst/htmlwidgets/bpmnVisualization.yaml
  inst/htmlwidgets/lib/bpmn-visualization/bpmn-visualization.min.js
  man/bpmnVisualization-package.Rd
  man/bpmnVisualization-shiny.Rd
  man/display.Rd
Labels: enhancement

#31 [INFRA] Setup release-drafter for release notes inialization
  .github/release-drafter.yml
  .github/workflows/fill-gh-draft-release.yml
Labels: infra:repo

#27 [FEAT] Update API to display BPMN Elements with Overlays
  NAMESPACE
  R/bpmnVisualization.R
  README.md
  inst/htmlwidgets/bpmnVisualization.js
  man/create_overlay.Rd
  man/display.Rd
Labels: enhancement

#36 [DOC] Explain where the BPMN diagram examples come from
  README.md
Labels: documentation

#38 [FIX] Fix the error when there is no overlay
  inst/htmlwidgets/bpmnVisualization.js
Labels: bug
