Repository process-analytics/bpmn-visualization-R, pull requests merged in 2022-08, with the labels that each got.

#100 [INFRA] Update wording in the GH WF bumping bpmn-visualization
  .github/workflows/update_bpmn_visualization_version.yml
Labels: infra:repo

#105 [DOC] Do not add dev dependencies to release notes
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/fill-gh-draft-release.yml
Labels: documentation

#107 [RELEASE] Set version to 0.2.0
  CONTRIBUTING.md
  DESCRIPTION
  README.md
Labels: skip-changelog
