Repository process-analytics/bpmn-visualization-R, pull requests merged in 2022-10, with the labels that each got.

#117 [INFRA] Adding tests
  DESCRIPTION
  R/bpmnVisualization.R
  R/funs.R
  tests/testthat.R
  tests/testthat/test-bpmnVisualization.R
  tests/testthat/test-funs.R
Labels: hacktoberfest-accepted, chore

#124 [DOC] Improve the documentation to better match CRAN requirements
  DESCRIPTION
  R/bpmnVisualization.R
  R/funs.R
  README.md
  inst/examples/Order_Management.bpmn
  man/bpmnVisualization-shiny-output.Rd
  man/bpmnVisualization-shiny-render.Rd
  man/bpmnVisualization-shiny.Rd
  man/create_overlay.Rd
  man/display.Rd
Labels: documentation

#132 [DOC] Improve the release process
  CONTRIBUTING.md
  MAINTAINERS.md
Labels: documentation

#133 [RELEASE] Set version to 0.2.1
  DESCRIPTION
  README.md
Labels: skip-changelog

#135 [DOC] Change the project email
  DESCRIPTION
Labels: documentation
