Repository process-analytics/bpmn-visualization-R, pull requests merged in 2022-04, with the labels that each got.

#75 [INFRA] Fix the milestone link in the release-drafter configuration
  .github/release-drafter.yml
Labels: infra:repo

#34 [INFRA] Automate bpmn-visualization-js update
  .github/workflows/update_bpmn_visualization_version.yml
Labels: infra:repo

#79 [INFRA] Improve usage of the r-lib action
  .github/workflows/R-CMD-check.yaml
Labels: infra:build

#78 [DOC] Clean SVG hero
  doc/example_email_voting_with_overlays.svg
Labels: documentation

#80 [DOC] Update how to "update BPMN Visualization version"
  CONTRIBUTING.md
Labels: documentation
