Repository process-analytics/bpmn-visualization-R, pull requests merged in 2022-03, with the labels that each got.

#65 [INFRA] Bump 'bpmn-visualization' from 0.19.4 to 0.23.0
  inst/htmlwidgets/bpmnVisualization.yaml
  inst/htmlwidgets/lib/bpmn-visualization/bpmn-visualization.min.js
Labels: dependencies

#67 [INFRA] Configure dependabot for gha update
  .github/dependabot.yml
Labels: infra:build

#66 [INFRA] Improve the release-notes generation
  .github/release-drafter.yml
  .github/workflows/fill-gh-draft-release.yml
Labels: infra:repo

#71 [EXAMPLE] Improve waypoints in the 'email voting' diagram
  inst/examples/Email_Voting.bpmn
Labels: enhancement

#70 [DOC] Explain how to install a specific version
  CONTRIBUTING.md
  README.md
Labels: documentation

#72 [DOC] Update the hero image
  README.md
  doc/example_email_voting_with_overlays.png
  doc/example_email_voting_with_overlays.svg
Labels: documentation

#74 [RELEASE] Set version to 0.1.2
  CONTRIBUTING.md
  DESCRIPTION
  README.md
Labels: infra:build
