Repository process-analytics/bpmn-visualization-R, pull requests merged in 2023-09, with the labels that each got.

#245 feat(style)!: refactor how to build the overlay style
  NAMESPACE
  R/bpmnVisualizationR.R
  R/funs.R
  README.md
  man/create_fill.Rd
  man/create_font.Rd
  man/create_overlay.Rd
  man/create_overlay_style.Rd
  man/create_stroke.Rd
  man/create_style.Rd
  man/display.Rd
  man/overlay_edge_position.Rd
  man/overlay_shape_position.Rd
  tests/testthat/test-funs.R
Labels: documentation, enhancement, refactoring

#246 docs: enabling markdown support
  DESCRIPTION
  R/bpmnVisualizationR.R
  R/funs.R
  man/bpmnVisualizationR-shiny-output.Rd
  man/create_overlay.Rd
  man/create_overlay_style.Rd
  man/display.Rd
  man/overlay_edge_position.Rd
  man/overlay_shape_position.Rd
Labels: documentation

#248 refactor: simplify overlay management in JS bridge code
  inst/htmlwidgets/bpmnVisualizationR.js
Labels: refactoring

#249 ci(release): eliminate bypassing of branch protection
  .github/workflows/release.yml
Labels: chore

#250 docs: describe the security policy
  SECURITY.md
Labels: documentation

#247 feat: allow to style BPMN Elements
  NAMESPACE
  R/bpmnVisualizationR.R
  R/funs.R
  README.md
  doc/example_email_voting_with_overlays.svg
  inst/htmlwidgets/bpmnVisualizationR.js
  man/create_edge_style.Rd
  man/create_element_style.Rd
  man/create_gradient_fill.Rd
  man/create_overlay_style.Rd
  man/create_shape_style.Rd
  man/display.Rd
  tests/testthat/test-funs.R
Labels: enhancement

#255 docs: improve CRAN publishing how-to
  MAINTAINERS.md
Labels: documentation
